kind: Service
apiVersion: v1
metadata:
  name: nfs-server
# ClusterIP by default === only reachable within the cluster
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    # Find nfs-server deployment
    role: nfs-server
