apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  # NFS volume
  nfs:
    server: nfs-server.default.svc.cluster.local  # symbolic name, rather than hardcoded one
    path: "/"
  # Configure NFS options via PV
  mountOptions:
    - nfsvers=4.2
